language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - nightly

matrix:
  allow_failures:
    - python: nightly

install:
  - pip install --quiet coveralls

script:
  - nosetests --with-coverage --cover-package=yapf

after_success:
  - coveralls
